AutoBody/Models/ClientAPI.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AutoBody.Models
{
    public class ClientAPI
    {
        private string[] apiCalls =
            {
                "AddArrival",
                "AddOrUpdateClients",
                "GetClients",
                "GetCustomClientFields",
                "GetClientIndexes",
                "GetClientContactLogs",
                "AddOrUpdateContactLogs",
                "GetContactLogTypes",
                "UploadClientDocument",
                "GetClientReferralTypes",
                "GetActiveClientMemberships",
                "GetClientContracts",
                "GetClientAccountBalances",
                "GetClientServices",
                "GetClientVisits",
                "GetClientPurchases",
                "GetClientSchedule",
                "GetRequiredClientFields",
                "ValidateLogin",
                "UpdateClientServices",
                "SendUserNewPassword"
            };

        public string[] getClientServiceAPI()
        {
            return apiCalls;
        }

        public static ClientService.UserCredentials getUserCredentials(APIModel model)
        {
            return new ClientService.UserCredentials
            {
                Password = model.Password,
                SiteIDs = new[] { model.SiteID },
                Username = model.Username
            };
        }

        public static ClientService.SourceCredentials getSourceCredentials(APIModel model)
        {
            return new ClientService.SourceCredentials
            {
                Password = model.SourcePassword,
                SiteIDs = new[] { model.SiteID },
                SourceName = model.SourceName
            };
        }
    }

    public class GetClientsModel : APIModel
    {
        [Display(Name = "ClientIDs")]
        public string[] ClientIDs { get; set; }

        [Display(Name = "Search Text")]
        public string SearchText { get; set; }
    }
}

AutoBody/Controllers/ClientAPIController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using AutoBody.ClientService;
using AutoBody.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AutoBody.Controllers
{
    public class ClientAPIController : Controller
    {

        private ClientService.ClientService clientService = new ClientService.ClientService();

        public ActionResult Index()
        {
            return Redirect("/Home/ClientService");
        }

        public ActionResult GetClients()
        {
            ViewBag.Credentials = new APISettings();
            return View();
        }


/*****************************************  Get Clients  *********************************************/


        private ClientService.GetClientsRequest getClients(GetClientsModel model)
        {
            var request = APISettings.getBaseClientRequest<GetClientsRequest>(model);

            request.ClientIDs = model.ClientIDs;
            request.SearchText = model.SearchText;

            return request;
        }

        public ActionResult GetClientsRequest(GetClientsModel model)
        {
            var request = getClients(model);
            var response = clientService.GetClients(request);

            @ViewBag.Request_JSON = JsonConvert.SerializeObject(request, Formatting.Indented, new JsonConverter[] { new StringEnumConverter() });
            @ViewBag.Response_JSON = JsonConvert.SerializeObject(response, Formatting.Indented, new JsonConverter[] { new StringEnumConverter() });

            @ViewBag.Request_SOAP = SoapSerializer.SerializeToSoap<GetClientsRequest>(request);
            @ViewBag.Response_SOAP = SoapSerializer.SerializeToSoap<GetClientsResult>(response);

            return View();
        }

        
    }
}

AutoBody/Views/ClientAPI/GetClients.cshtml
@model AutoBody.Models.GetClientsModel

@{
    ViewBag.Title = "GetClients";
}

<h2>GetStaffAppointments</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

@using (Html.BeginForm("GetClientsRequest", "ClientAPI", FormMethod.Get))
{
    @Html.ValidationSummary()
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Required</li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SourceName)
            @Html.TextBoxFor(m => m.SourceName, new { @Value = ViewBag.Credentials.SourceName})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SourcePassword)
            @Html.TextBoxFor(m => m.SourcePassword, new { @Value = ViewBag.Credentials.SourcePassword})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Username)
            @Html.TextBoxFor(m => m.Username, new { @Value = ViewBag.Credentials.Username})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Password)
            @Html.TextBoxFor(m => m.Password, new { @Value = ViewBag.Credentials.Password})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SiteID)
            @Html.TextBoxFor(m => m.SiteID, new { @Value = ViewBag.Credentials.SiteID})
        </li>
        
    </ul>
    
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Optional</li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.ClientIDs)
            @Html.TextBoxFor(m => m.ClientIDs)
        </li>

        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SearchText)
            @Html.TextBoxFor(m => m.SearchText)
        </li>

        <li data-role="fieldcontain">
            <input type="submit" value="Send Request" />
        </li>
    </ul>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutoBody/Views/ClientAPI/GetClientsRequest.cshtml
@{
    ViewBag.Title = "GetClientsRequest";
}

<h2>GetStaffAppointments Result</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

<h1>Request</h1>


<div id="request-nav" data-role="navbar">
    <ul>
        <li><a href="#request-soap">Soap</a></li>
        <li><a href="#request-json">JSON</a></li>
    </ul>
</div>
<br />

<div class="code-box" id ="request">
    <div id="request-soap">
        <pre style="font-size: 20px">@ViewBag.Request_SOAP</pre>
    </div>

    <div id="request-json" style="display: none">
        <pre style="font-size: 20px">@ViewBag.Request_JSON</pre>
    </div>
</div>


<h1>Response</h1>
<div id="response-nav" data-role="navbar">
    <ul>
        <li><a href="#response-soap">Soap</a></li>
        <li><a href="#response-json">JSON</a></li>
    </ul>
</div>
<br />

<div class="code-box" id ="response">
    <div id="response-soap">
        <pre style="font-size: 20px">@ViewBag.Response_SOAP</pre>
    </div>

    <div id="response-json" style="display: none">
        <pre style="font-size: 20px">@ViewBag.Response_JSON</pre>
    </div>
</div>