AutoBody/Models/AppointmentAPI.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoBody.AppointmentService;

namespace AutoBody.Models
{
    public class AppointmentAPI
    {
        private string[] apiCalls =
            {
                "GetStaffAppointments",
                "AddOrUpdateAppointments",
                "GetBookableItems",
                "GetScheduleItems",
                "AddOrUpdateAvailabilities",
                "GetActiveSessionTimes",
                "GetAppointmentOptions"
            };

        public string[] getAppointmentServiceAPI()
        {
            return apiCalls;
        }
    }

    public class GetStaffAppointmentsModel : APIModel
    {
        [Required]
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }

        [Required]
        [Display(Name = "End Date")]
        public DateTime EndDate { get; set; }
    }

    public class AddOrUpdateAppointmentsModel : APIModel
    {
        [Display(Name = "Update Action")]
        public string UpdateAction { get; set; }

        [Display(Name = "Test")]
        public bool Test { get; set; }

        [Display(Name = "Send Email")]
        public bool SendEmail { get; set; }

        [Display(Name = "Apply Payment")]
        public bool ApplyPayment { get; set; }

        [Display(Name = "Appointments")]
        public AppointmentModel [] Appointments { get; set; }

        [HiddenInput(DisplayValue = true)]
        public int appointmentsCount { get; set; }
    }

    public class GetBookableItemsModel : APIModel
    {
        [Display(Name = "Session Type IDs")]
        public int[] SessionTypeIDs { get; set; }

        [Display(Name = "Location IDs")]
        public int[] LocationIDs { get; set; }

        [Display(Name = "Staff IDs")]
        public long[] StaffIDs { get; set; }

        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        public DateTime EndDate { get; set; }
    }

    public class GetScheduleItemsModel : APIModel
    {
        [Display(Name = "Location IDs")]
        public int[] LocationIDs { get; set; }

        [Display(Name = "Staff IDs")]
        public long[] StaffIDs { get; set; }

        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        public DateTime EndDate { get; set; }

        [Display(Name = "Ignore Prep Finish Times")]
        public bool IgnorePrepFinishTimes { get; set; }
    }

    public class AddOrUpdateAvailabilitiesModel : APIModel
    {
        [Display(Name = "Update Action")]
        public string UpdateAction { get; set; }

        [Display(Name = "Test")]
        public bool Test { get; set; }

        [Display(Name = "Availablity IDs")]
        public int[] AvalibilityIDs { get; set; }

        [Display(Name = "Location IDs")]
        public int LocationID { get; set; }

        [Display(Name = "Staff IDs")]
        public long[] StaffIDs { get; set; }

        [Display(Name = "Program IDs")]
        public int[] ProgramIDs { get; set; }

        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        public DateTime EndDate { get; set; }

        [Display(Name = "Days of Week")]
        public AppointmentService.DayOfWeek [] DaysOfWeek { get; set; }

        [Display(Name = "Unavailable Description")]
        public string UnavailableDescription { get; set; }

        [Display(Name = "Is Unavailable")]
        public bool IsUnavailable { get; set; }

        [Display(Name = "Public Display")]
        public AppointmentService.AvailabilityDisplay PublicDisplay { get; set; }
    }

    public class GetActiveSessionTimesModel : APIModel
    {
        [Display(Name = "Schedule Type")]
        public AppointmentService.ScheduleType ScheduleType { get; set; }

        [Display(Name = "Session Type IDs")]
        public int[] SessionTypeIDs { get; set; }

        [Display(Name = "Start Date")]
        public DateTime StartTime { get; set; }

        [Display(Name = "End Date")]
        public DateTime EndTime { get; set; }
    }

    public class GetAppointmentOptionsModel : APIModel
    {
        //Empty request, but need to follow design scheme
    }
}

AutoBody/Controllers/AppointmentAPIController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoBody.AppointmentService;
using AutoBody.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AutoBody.Controllers
{
    public class AppointmentAPIController : Controller
    {
        //
        // GET: /Appointment/

        private AppointmentService.AppointmentService appointmentService = new AppointmentService.AppointmentService();

        public ActionResult Index()
        {
            return Redirect("/Home/AppointmentService");
        }

        public static AppointmentService.UserCredentials getUserCredentials(APIModel model)
        {
            return new AppointmentService.UserCredentials
            {
                Password = model.Password,
                SiteIDs = new[] { model.SiteID },
                Username = model.Username
            };
        }

        public static AppointmentService.SourceCredentials getSourceCredentials(APIModel model)
        {
            return new AppointmentService.SourceCredentials
            {
                Password = model.SourcePassword,
                SiteIDs = new[] { model.SiteID },
                SourceName = model.SourceName
            };
        }

        public static AppointmentService.StaffCredentials getStaffCredentials(APIModel model)
        {
            return new AppointmentService.StaffCredentials
            {
                Password = model.StaffPassword,
                SiteIDs = new[] { model.SiteID },
                Username = model.StaffName
            };
        }


        /***********************************************GetStaffAppointments*********************************************************/

        public ActionResult GetStaffAppointments()
        {
            ViewBag.Credentials = new APISettings();
            return View();
        }

        private GetStaffAppointmentsRequest getStaffAppointments(GetStaffAppointmentsModel model)
        {
            var request = APISettings.getBaseAppointmentRequest<GetStaffAppointmentsRequest>(model);

            System.Diagnostics.Debug.WriteLine("Request is: " + request);

            request.StaffIDs = new long[] {model.StaffID};
            request.StartDate = model.StartDate;
            request.EndDate = model.EndDate;


            return request;
        }

        public ActionResult GetStaffAppointmentsRequest(GetStaffAppointmentsModel model)
        {
            var request = getStaffAppointments(model);
            var response = appointmentService.GetStaffAppointments(request);

            @ViewBag.Request_JSON = JsonConvert.SerializeObject(request, Formatting.Indented, new JsonConverter[] { new StringEnumConverter() });
            @ViewBag.Response_JSON = JsonConvert.SerializeObject(response, Formatting.Indented, new JsonConverter[] { new StringEnumConverter() });

            @ViewBag.Request_SOAP = SoapSerializer.SerializeToSoap<GetStaffAppointmentsRequest>(request);
            @ViewBag.Response_SOAP = SoapSerializer.SerializeToSoap<GetStaffAppointmentsResult>(response);

            return View();
        }

        /**********************************************AddOrUpdateAppointments******************************************************/
        //This is a hefty-ass one

        private AppointmentService.Program getProgram(AddOrUpdateAppointmentsModel model, int index)
        {
            return new AppointmentService.Program
                       {
                           ID = model.Appointments[index].appt_Program.prgm_ID,
                           Name = model.Appointments[index].appt_Program.prgm_Name
                       };
        }

        private AppointmentService.SessionType getSessionType(AddOrUpdateAppointmentsModel model, int index)
        {
            return new AppointmentService.SessionType
                       {
                           ID = model.Appointments[index].appt_SessionType.sestp_ID,
                           Name = model.Appointments[index].appt_SessionType.sestp_Name,

                           IDSpecified = model.Appointments[index].appt_SessionType.sestp_ID >= 0
                       };
        }

        private AppointmentService.Location getLocation(AddOrUpdateAppointmentsModel model, int index)
        {
            return new AppointmentService.Location
                       {
                           BusinessID = model.Appointments[index].appt_Location.loc_BusinessID,
                           SiteID = model.Appointments[index].appt_Location.loc_SiteID,
                           BusinessDescription = model.Appointments[index].appt_Location.loc_BusinessDescription,
                           AdditionalImageURLs = ("," + model.Appointments[index].appt_Location.loc_AddImageUrls).Split(','),
                           FacilitySquareFeet = model.Appointments[index].appt_Location.loc_FacilitySqFt,
                           TreatmentRooms = model.Appointments[index].appt_Location.loc_TreamentRooms,
                           ProSpaFinderSite = model.Appointments[index].appt_Location.loc_SpaFinderSite,
                           HasClasses = model.Appointments[index].appt_Location.loc_HasClasses,
                           PhoneExtension = model.Appointments[index].appt_Location.loc_PhoneExt,
                           ID = model.Appointments[index].appt_Location.loc_ID,
                           Name = model.Appointments[index].appt_Location.loc_Name,
                           Latitude = model.Appointments[index].appt_Location.loc_Latitude,
                           Longitude = model.Appointments[index].appt_Location.loc_Longitude,
                           DistanceInMiles = model.Appointments[index].appt_Location.loc_DistanceInMiles,
                           ImageURL = model.Appointments[index].appt_Location.loc_ImageURL,
                           Description = model.Appointments[index].appt_Location.loc_Description,
                           HasSite = model.Appointments[index].appt_Location.loc_HasSite,
                           CanBook = model.Appointments[index].appt_Location.loc_CanBook
                       };
        }

        private AppointmentService.Staff getStaff(AddOrUpdateAppointmentsModel model, int index)
        {
            return new AppointmentService.Staff
                       {
                           Email = model.Appointments[index].appt_Staff.staff_Email,
                           MobilePhone = model.Appointments[index].appt_Staff.staff_MobilePhone,
                           HomePhone = model.Appointments[index].appt_Staff.staff_HomePhone,
                           WorkPhone = model.Appointments[index].appt_Staff.staff_WorkPhone,
                           Address = model.Appointments[index].appt_Staff.staff_Address,
                           Address2 = model.Appointments[index].appt_Staff.staff_Address2,
                           City = model.Appointments[index].appt_Staff.staff_City,
                           State = model.Appointments[index].appt_Staff.staff_State,
                           Country = model.Appointments[index].appt_Staff.staff_Country,
                           PostalCode = model.Appointments[index].appt_Staff.staff_PostalCode,
                           ForeignZip = model.Appointments[index].appt_Staff.staff_ForeignZip,
                           ID = model.Appointments[index].appt_Staff.staff_ID,
                           Name = model.Appointments[index].appt_Staff.staff_Name,
                           FirstName = model.Appointments[index].appt_Staff.staff_FirstName,
                           LastName = model.Appointments[index].appt_Staff.staff_LastName
                       };
        }

        private AppointmentService.Client getClient(AddOrUpdateAppointmentsModel model, int index)
        {
            return new AppointmentService.Client
                       {
                           ID = model.Appointments[index].appt_Client.clt_ID,
                           FirstName = model.Appointments[index].appt_Client.clt_FirstName,
                           LastName = model.Appointments[index].appt_Client.clt_LastName,
                           Email = model.Appointments[index].appt_Client.clt_Email,
                           MobilePhone = model.Appointments[index].appt_Client.clt_MobilePhone,
                           HomePhone = model.Appointments[index].appt_Client.clt_HomePhone
                       };
        }

        private AppointmentService.ClientService getClientService(AddOrUpdateAppointmentsModel model, int index)
        {
            return new AppointmentService.ClientService
                       {
                           ID = model.Appointments[index].appt_ClientService.cltsv_ID,
                           Name = model.Appointments[index].appt_ClientService.cltsv_Name
                       };
        }

        //TODO Support multiple resources
        private AppointmentService.Resource[] getResources(AddOrUpdateAppointmentsModel model, int index)
        {
            return new []
                       {
                           new Resource
                               {
                                   ID = model.Appointments[index].appt_Resources[0].res_ID,
                                   Name = model.Appointments[index].appt_Resources[0].res_Name
                               }
                       };
        }

        private AppointmentService.Appointment[] getAppointments(AddOrUpdateAppointmentsModel model)
        {
            var appointments = new List<AppointmentService.Appointment>();
            System.Diagnostics.Debug.WriteLine("appointmentsCount is " + model.appointmentsCount);
            for (int i = 0; i < model.appointmentsCount; i++)
            {
                var appointment = new Appointment
                                      {
                                          ID = model.Appointments[i].appt_ID,

AutoBody/Views/AppointmentAPI/AddOrUpdateAppointmentsRequest.cshtml
@{
    ViewBag.Title = "AddOrUpdateAppointmentsRequest";
}

<h2>AddOrUpdateAppointments Result</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

<h1>Request</h1>


<div id="request-nav" data-role="navbar">
    <ul>
        <li><a href="#request-soap">Soap</a></li>
        <li><a href="#request-json">JSON</a></li>
    </ul>
</div>
<br />

<div class="code-box" id ="request">
    <div id="request-soap">
        <pre style="font-size: 20px">@ViewBag.Request_SOAP</pre>
    </div>

    <div id="request-json" style="display: none">
        <pre style="font-size: 20px">@ViewBag.Request_JSON</pre>
    </div>
</div>


<h1>Response</h1>
<div id="response-nav" data-role="navbar">
    <ul>
        <li><a href="#response-soap">Soap</a></li>
        <li><a href="#response-json">JSON</a></li>
    </ul>
</div>
<br />

<div class="code-box" id ="response">
    <div id="response-soap">
        <pre style="font-size: 20px">@ViewBag.Response_SOAP</pre>
    </div>

    <div id="response-json" style="display: none">
        <pre style="font-size: 20px">@ViewBag.Response_JSON</pre>
    </div>
</div>

AutoBody/Views/AppointmentAPI/AddOrUpdateAvailabilities.cshtml
@model AutoBody.Models.AddOrUpdateAvailabilitiesModel

@{
    ViewBag.Title = "AddOrUpdateAvailabilities";
}

<h2>GetStaffAppointments</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

@using (Html.BeginForm("AddOrUpdateAvailabilitiesRequest", "AppointmentAPI", FormMethod.Get))
{
    @Html.ValidationSummary()
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Required</li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SourceName)
            @Html.TextBoxFor(m => m.SourceName, new { @Value = ViewBag.Credentials.SourceName})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SourcePassword)
            @Html.TextBoxFor(m => m.SourcePassword, new { @Value = ViewBag.Credentials.SourcePassword})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Username)
            @Html.TextBoxFor(m => m.Username, new { @Value = ViewBag.Credentials.Username})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Password)
            @Html.TextBoxFor(m => m.Password, new { @Value = ViewBag.Credentials.Password})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SiteID)
            @Html.TextBoxFor(m => m.SiteID, new { @Value = ViewBag.Credentials.SiteID})
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.LocationID)
            @Html.TextBoxFor(m => m.LocationID)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.StartDate)
            @Html.TextBoxFor(m => m.StartDate)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.EndDate)
            @Html.TextBoxFor(m => m.EndDate)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.UnavailableDescription)
            @Html.TextBoxFor(m => m.UnavailableDescription)
        </li>
        
    </ul>
    
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Optional</li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.UpdateAction)
            @Html.TextBoxFor(m => m.UpdateAction)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Test)
            @Html.CheckBoxFor(m => m.Test)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.AvalibilityIDs)
            @Html.TextBoxFor(m => m.AvalibilityIDs)
        </li>
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.StaffIDs)
            @Html.TextBoxFor(m => m.StaffIDs)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.ProgramIDs)
            @Html.TextBoxFor(m => m.ProgramIDs)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.DaysOfWeek)
            @Html.TextBoxFor(m => m.DaysOfWeek)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.IsUnavailable)
            @Html.CheckBoxFor(m => m.IsUnavailable)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.PublicDisplay)
            @Html.TextBoxFor(m => m.PublicDisplay)
        </li>

        <li data-role="fieldcontain">
            <input type="submit" value="Send Request" />
        </li>
    </ul>
}

AutoBody/Views/AppointmentAPI/GetActiveSessionTimes.cshtml
@model AutoBody.Models.GetActiveSessionTimesModel

@{
    ViewBag.Title = "GetActiveSessionTimes";
}

<h2>GetStaffAppointments</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

@using (Html.BeginForm("GetActiveSessionTimesRequest", "AppointmentAPI", FormMethod.Get))
{
    @Html.ValidationSummary()
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Required</li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SourceName)
            @Html.TextBoxFor(m => m.SourceName, new { @Value = ViewBag.Credentials.SourceName})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SourcePassword)
            @Html.TextBoxFor(m => m.SourcePassword, new { @Value = ViewBag.Credentials.SourcePassword})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Username)
            @Html.TextBoxFor(m => m.Username, new { @Value = ViewBag.Credentials.Username})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Password)
            @Html.TextBoxFor(m => m.Password, new { @Value = ViewBag.Credentials.Password})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SiteID)
            @Html.TextBoxFor(m => m.SiteID, new { @Value = ViewBag.Credentials.SiteID})
        </li>
        
    </ul>
    
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Optional</li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.ScheduleType)
            @Html.TextBoxFor(m => m.ScheduleType)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SessionTypeIDs)
            @Html.TextBoxFor(m => m.SessionTypeIDs)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.StartTime)
            @Html.TextBoxFor(m => m.StartTime)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.EndTime)
            @Html.TextBoxFor(m => m.EndTime)
        </li>

        <li data-role="fieldcontain">
            <input type="submit" value="Send Request" />
        </li>
    </ul>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutoBody/Views/AppointmentAPI/GetAppointmentOptions.cshtml
@model AutoBody.Models.GetAppointmentOptionsModel

@{
    ViewBag.Title = "GetAppointmentOptions";
}

<h2>GetStaffAppointments</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

@using (Html.BeginForm("GetAppointmentOptionsRequest", "AppointmentAPI", FormMethod.Get))
{
    @Html.ValidationSummary()
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Required</li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SourceName)
            @Html.TextBoxFor(m => m.SourceName, new { @Value = ViewBag.Credentials.SourceName})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SourcePassword)
            @Html.TextBoxFor(m => m.SourcePassword, new { @Value = ViewBag.Credentials.SourcePassword})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Username)
            @Html.TextBoxFor(m => m.Username, new { @Value = ViewBag.Credentials.Username})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Password)
            @Html.TextBoxFor(m => m.Password, new { @Value = ViewBag.Credentials.Password})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SiteID)
            @Html.TextBoxFor(m => m.SiteID, new { @Value = ViewBag.Credentials.SiteID})
        </li>

        <li data-role="fieldcontain">
            <input type="submit" value="Send Request" />
        </li>
    </ul>
}

AutoBody/Views/AppointmentAPI/GetBookableItems.cshtml
@model AutoBody.Models.GetBookableItemsModel

@{
    ViewBag.Title = "GetBookableItems";
}

<h2>GetStaffAppointments</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

@using (Html.BeginForm("GetBookableItemsRequest", "AppointmentAPI", FormMethod.Get))
{
    @Html.ValidationSummary()
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Required</li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SourceName)
            @Html.TextBoxFor(m => m.SourceName, new { @Value = ViewBag.Credentials.SourceName})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SourcePassword)
            @Html.TextBoxFor(m => m.SourcePassword, new { @Value = ViewBag.Credentials.SourcePassword})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Username)
            @Html.TextBoxFor(m => m.Username, new { @Value = ViewBag.Credentials.Username})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Password)
            @Html.TextBoxFor(m => m.Password, new { @Value = ViewBag.Credentials.Password})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SiteID)
            @Html.TextBoxFor(m => m.SiteID, new { @Value = ViewBag.Credentials.SiteID})
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SessionTypeIDs)
            @Html.TextBoxFor(m => m.SessionTypeIDs)
        </li>
        
    </ul>
    
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Optional</li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.LocationIDs)
            @Html.TextBoxFor(m => m.LocationIDs)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.StaffIDs)
            @Html.TextBoxFor(m => m.StaffIDs)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.StartDate)
            @Html.TextBoxFor(m => m.StartDate)
        </li>
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.EndDate)
            @Html.TextBoxFor(m => m.EndDate)
        </li>

        <li data-role="fieldcontain">
            <input type="submit" value="Send Request" />
        </li>
    </ul>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutoBody/Views/AppointmentAPI/GetScheduleItems.cshtml
@model AutoBody.Models.GetScheduleItemsModel

@{
    ViewBag.Title = "GetBookableItems";
}

<h2>GetStaffAppointments</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

@using (Html.BeginForm("GetScheduleItemsRequest", "AppointmentAPI", FormMethod.Get))
{
    @Html.ValidationSummary()
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Required</li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SourceName)
            @Html.TextBoxFor(m => m.SourceName, new { @Value = ViewBag.Credentials.SourceName})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SourcePassword)
            @Html.TextBoxFor(m => m.SourcePassword, new { @Value = ViewBag.Credentials.SourcePassword})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Username)
            @Html.TextBoxFor(m => m.Username, new { @Value = ViewBag.Credentials.Username})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.Password)
            @Html.TextBoxFor(m => m.Password, new { @Value = ViewBag.Credentials.Password})            
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.SiteID)
            @Html.TextBoxFor(m => m.SiteID, new { @Value = ViewBag.Credentials.SiteID})
        </li>
        
    </ul>
    
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Optional</li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.LocationIDs)
            @Html.TextBoxFor(m => m.LocationIDs)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.StaffIDs)
            @Html.TextBoxFor(m => m.StaffIDs)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.StartDate)
            @Html.TextBoxFor(m => m.StartDate)
        </li>
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.EndDate)
            @Html.TextBoxFor(m => m.EndDate)
        </li>
        
        <li data-role="fieldcontain">
            @Html.LabelFor(m => m.IgnorePrepFinishTimes)
            @Html.CheckBoxFor(m => m.IgnorePrepFinishTimes)
        </li>

        <li data-role="fieldcontain">
            <input type="submit" value="Send Request" />
        </li>
    </ul>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}