AutoBody/Controllers/ClassAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoBody.AppointmentService;
using AutoBody.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AutoBody.Controllers
{
    public class ClassAPIController : Controller
    {
        //
        // GET: /Appointment/

        private ClassService.ClassService classService = new ClassService.ClassService();

        public ActionResult Index()
        {
            return Redirect("/Home/ClassService");
        }
    }
}

AutoBody/Controllers/DataAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoBody.AppointmentService;
using AutoBody.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AutoBody.Controllers
{
    public class DataAPIController : Controller
    {
        //
        // GET: /Appointment/

        private DataService.DataService dataService = new DataService.DataService();

        public ActionResult Index()
        {
            return Redirect("/Home/DataService");
        }
    }
}

AutoBody/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoBody.ClassService;
using AutoBody.Models;
using Staff = AutoBody.StaffService.Staff;

namespace AutoBody.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template so that you do not appear noobish.";
            ViewBag.Message2 = "This was completely designed by Hammer.";
            ViewBag.Notice = "Most API calls are managed using GET variables. However, due to the length restriction " +
                             "of URLs, certain methods must be managed through POST variables and are marked accordingly.";
            return View();
        }

        

        public ActionResult AppointmentService()
        {
            ViewBag.Message = "AppointmentService API Methods";

            var api = new AppointmentAPI();
            ViewBag.apiCalls = api.getAppointmentServiceAPI();

            return View();
        }

        public ActionResult ClassService()
        {
            ViewBag.Message = "ClassService API Methods";

            var api = new ClassAPI();
            ViewBag.apiCalls = api.getClassServiceAPI();

            return View();
        }

        public ActionResult ClientService()
        {
            ViewBag.Message = "ClientService API Methods";

            var api = new ClientAPI();
            ViewBag.apiCalls = api.getClientServiceAPI();

            return View();
        }

        public ActionResult DataService()
        {
            ViewBag.Message = "DataService API Methods";

            var api = new DataAPI();
            ViewBag.apiCalls = api.getDataServiceAPI();

            return View();
        }

        public ActionResult FinderService()
        {
            ViewBag.Message = "FinderService API Methods";

            var api = new FinderAPI();
            ViewBag.apiCalls = api.getFinderServiceAPI();

            return View();
        }

        public ActionResult SaleService()
        {
            ViewBag.Message = "SaleService API Methods";

            var api = new SaleAPI();
            ViewBag.apiCalls = api.getSaleServiceAPI();

            return View();
        }

        public ActionResult SiteService()
        {
            ViewBag.Message = "SiteService API Methods";

            var api = new SiteAPI();
            ViewBag.apiCalls = api.getSiteServiceAPI();

            return View();
        }

        public ActionResult StaffService()
        {
            ViewBag.Message = "StaffService API Methods";

            var api = new StaffAPI();
            ViewBag.apiCalls = api.getStaffServiceAPI();

            return View();
        }
    }
}

AutoBody/Controllers/SaleAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoBody.AppointmentService;
using AutoBody.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AutoBody.Controllers
{
    public class SaleAPIController : Controller
    {
        //
        // GET: /Appointment/

        private SaleService.SaleService saleService = new SaleService.SaleService();

        public ActionResult Index()
        {
            return Redirect("/Home/SaleService");
        }
    }
}

AutoBody/Controllers/SiteAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoBody.AppointmentService;
using AutoBody.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AutoBody.Controllers
{
    public class SiteAPIController : Controller
    {
        //
        // GET: /Appointment/

        private SiteService.SiteService siteService = new SiteService.SiteService();

        public ActionResult Index()
        {
            return Redirect("/Home/SiteService");
        }
    }
}

AutoBody/Views/Home/AppointmentService.cshtml
@{
    ViewBag.Title = "AppointmentService";
}

<h2>AppointmentService</h2>

<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

<ul data-role="listview" data-inset="true">
    @foreach (string call in ViewBag.apiCalls)
    {
        <li>@Html.ActionLink(@call, @call, "AppointmentAPI")</li>
    }
</ul>

AutoBody/Views/Home/Appointments.cshtml
@{
    ViewBag.Title = "Appointments";
}

<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("Back to Staff List", "AboutStaff", "Home")</li>
</ul>


<h2>Appointments for @ViewBag.staffId</h2>

        <ul>
        @{
            foreach (var appt in ViewBag.appts)
            {
                <li>@appt.Client.FirstName @appt.Client.LastName [<b>@appt.StartDateTime - @appt.EndDateTime</b>] </li>

            }
        }
        </ul>

AutoBody/Views/Home/ClassService.cshtml
@{
    ViewBag.Title = "ClassService";
}

<h2>ClassService</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

<ul data-role="listview" data-inset="true">
    @foreach (string call in ViewBag.apiCalls)
    {
        <li>@Html.ActionLink(@call, @call, "ClassAPI")</li>
    }
</ul>

AutoBody/Views/Home/ClientService.cshtml
@{
    ViewBag.Title = "ClientService";
}

<h2>ClientService</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

<ul data-role="listview" data-inset="true">
    @foreach (string call in ViewBag.apiCalls)
    {
        <li>@Html.ActionLink(@call, @call, "ClientAPI")</li>
    }
</ul>

AutoBody/Views/Home/DataService.cshtml
@{
    ViewBag.Title = "DataService";
}

<h2>DataService</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

<ul data-role="listview" data-inset="true">
    @foreach (string call in ViewBag.apiCalls)
    {
        <li>@Html.ActionLink(@call, @call, "DataAPI")</li>
    }
</ul>

AutoBody/Views/Home/FinderService.cshtml
@{
    ViewBag.Title = "FinderService";
}

<h2>FinderService</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

<ul data-role="listview" data-inset="true">
    @foreach (string call in ViewBag.apiCalls)
    {
        <li>@Html.ActionLink(@call, @call, "FinderAPI")</li>
    }
</ul>

AutoBody/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2><del>@ViewBag.Message</del></h2>
<h2>@ViewBag.Message2</h2>

<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("AppointmentService", "AppointmentService", "Home")</li>
    <li>@Html.ActionLink("ClassService", "ClassService", "Home")</li>
    <li>@Html.ActionLink("ClientService", "ClientService", "Home")</li>
    <li>@Html.ActionLink("DataService", "DataService", "Home")</li>
    <li>@Html.ActionLink("FinderService", "FinderService", "Home")</li>
    <li>@Html.ActionLink("SaleService", "SaleService", "Home")</li>
    <li>@Html.ActionLink("SiteService", "SiteService", "Home")</li>
    <li>@Html.ActionLink("StaffService", "StaffService", "Home")</li>
</ul>

<h3>@ViewBag.Notice</h3>

AutoBody/Views/Home/SaleService.cshtml
@{
    ViewBag.Title = "SaleService";
}

<h2>SaleService</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

<ul data-role="listview" data-inset="true">
    @foreach (string call in ViewBag.apiCalls)
    {
        <li>@Html.ActionLink(@call, @call, "SaleAPI")</li>
    }
</ul>

AutoBody/Views/Home/SiteService.cshtml
@{
    ViewBag.Title = "SiteService";
}

<h2>SiteService</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

<ul data-role="listview" data-inset="true">
    @foreach (string call in ViewBag.apiCalls)
    {
        <li>@Html.ActionLink(@call, @call, "SiteAPI")</li>
    }
</ul>

AutoBody/Views/Home/StaffService.cshtml
@{
    ViewBag.Title = "StaffService";
}

<h2>StaffService</h2>
<ul data-role="listview" data-inset="true">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
</ul>

<ul data-role="listview" data-inset="true">
    @foreach (string call in ViewBag.apiCalls)
    {
        <li>@Html.ActionLink(@call, @call, "StaffAPI")</li>
    }
</ul>